### ISSUE TITLE
How to get information about my subdomain?

### ISSUE THREAD

**Issue by wclarkey** [is-a-good-dev/Register#110]
How to get information about my subdomain?

_Originally posted by @ElonMusk49 in https://github.com/is-a-good-dev/Register/issues/109#issuecomment-1193130754_

What information are you after? Information about getting a new domain or about an existing one?

**Comment by wclarkey** [comment]
@ElonMusk49 Please reply here and not in a random Pull request that has no corrilation to yourself.

**Comment by ElonMusk49** [comment]
Opps Sorry
I was asking about mine existing one

**Comment by ElonMusk49** [comment]
How sorry
I was asking that after i apply and got everything right how can I access cpanel or anything like that ?

Does this subdomain also provide mail feature?

**Comment by ElonMusk49** [comment]
Basically how will I develop my website on this subdomains ?

**Comment by wclarkey** [comment]
This is a free service. We do not provide cpanel. You develop your website normally (HTML,CSS) then you find somewhere to host it such as GitHub Pages. Once you have done that you follow our [docs](https://docs.is-a-good.dev)

**Comment by wclarkey** [comment]
@ElonMusk49 This will be closed in 24 hours if you do not reply.
