### ISSUE TITLE
Did Not Connect: Potential Security Issue

### ISSUE THREAD

**Issue by tunganhtran** [is-a-good-dev/register#184]
**Firefox** 
Detected a potential security threat and did not continue to tungtran.is-a-good.dev because this website requires a secure connection.
What can you do about it?
tungtran.is-a-good.dev has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.
The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

**Chrome**
Your connection is not private
Attackers might be trying to steal your information from tungtran.is-a-good.dev (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_COMMON_NAME_INVALID

**My register**

{
  "repo": "https://github.com/tunganhtran/introduction-myself",

  "owner": {
    "username": "tunganhtran",
    "email": "tunganhtran94@gmail.com"
  },

  "target": {
    "CNAME": "tunganhtran.github.io"
  },

  "proxied": false
}

How can i solve this problem?

**Comment by Tweak4141** [comment]
Hi there. Please look at this article.
https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https
