### ISSUE TITLE
Can I use other repository page instead of the root?

### ISSUE THREAD

**Issue by nevenxr** [is-a-good-dev/Register#45]
Do you people allow `<username>.github.io/<repo>` or just `<username>.github.io`?

**Comment by wclarkey** [comment]
Normally only the root domain. I'm not sure whether that's something you can setup in GitHub Pages. I'll do some testing and let you know.

**Comment by wclarkey** [comment]
@nevenxr If the root GitHub domain links to a repo, this should be possible.
