### ISSUE TITLE
Just an Idea

### ISSUE THREAD

**Issue by Luuna6** [is-a-good-dev/register#498]
**Hi**
my idea is you making another repo for the process that you did go threw to make a service like this 
cuz that can change many things for devlopers for example me : you dont know how many time i got
a domain registerd for and did nothing with atleast at that time i would helped manny other to lunch 
there apps
i hope that you consider doing my suggestion

**Comment by Tweak4141** [comment]
Hi there @Luuna6,

Thank for for creating an issue. 
Please rewrite your statement above in coherent English, avoiding the use of slang and malapropism.
Once you do this we can then take your issue into consideration.

Thank you.

**Comment by Tweak4141** [comment]
If you would like to elaborate further on your idea, please do so.
