### ISSUE TITLE
Need help setting up Vercel

### ISSUE THREAD

**Issue by f4rrysh** [is-a-good-dev/register#508]
I've claimed `farish.is-a-good.dev` subdomain but I need help setting it up with Vercel. As of #507, everything looks correct but Vercel seems to can't verify the domain.
![image](https://github.com/is-a-good-dev/register/assets/131455435/70fe238f-1581-43e1-8a75-879838b4da9a)

Any help is appreciated. Thanks in advance.

**Comment by f4rrysh** [comment]
Contents of `farish.json`:
```json
{
  "repo": "https://github.com/f4rrysh/portfolio",
  "owner": {
    "username": "f4rrysh",
    "email": "hello.farish.irfan@gmail.com"
  },
  "target": {
    "CNAME": {
      "name": "f4rrysh",
      "value": "cname.vercel-dns.com"
    },
    "TXT": {
      "name": "_vercel", 
      "value": "vc-domain-verify=farish.is-a-good.dev,862d5f85b8744e29248b"
    }
  },
  "proxied": false
}
```

**Comment by f4rrysh** [comment]
I'm following [`hung.json`](https://github.com/is-a-good-dev/register/blob/main/sub-logs/hung.json) which seems correct since `hung.is-a-good.dev` is working. Everything seems to be correct for me too.

**Comment by Tweak4141** [comment]
Hi there, there are some issues with Vercel and Netlify, and as such we cannot provide support for this. I recommend you use Github Pages instead as that is fully supported.
