### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by wclarkey** [is-a-good-dev/Register#54]
ToDo list:
- Cloudflare API integration for automation 
- Website
- Dashboard (??)

**Comment by wclarkey** [comment]
> also maybe ci checks as well? im a maintainer for a larger project and we had been intergrating ci checks and it works really nice.

If i may ask, what are ci checks?

**Comment by MaskDuck** [comment]
![image](https://user-images.githubusercontent.com/70831061/164119124-79bf16ac-12b0-4198-b3f2-51d1ca5ba558.png)

**Comment by MaskDuck** [comment]
![image](https://user-images.githubusercontent.com/70831061/164119174-8c63ec29-1b0a-47a2-8095-fa50b8f9e0aa.png)
exactly this part.

**Comment by wclarkey** [comment]
Oh I see! The plan is to eventually have a dashboard so that there is no GitHub PR. But that will need some looking into.

**Comment by WilliamDavidHarrison** [comment]
dashboards would be a cool idea :D

**Comment by wclarkey** [comment]
> dashboards would be a cool idea :D

Lots planned, exams and college work getting in the way atm tho.

**Comment by ConnorDoesDev** [comment]
what would the dashboard do? e.x what features would it have

**Comment by wclarkey** [comment]
> what would the dashboard do? e.x what features would it have 

Be a more automatic way of managing your subdomain and allow you to edit records delete the domain etc. Probably will have more features such as additional domains other than is-a-good.dev and maybe url forwarding

**Comment by wclarkey** [comment]
We will be working on a website soon anyways, that may bring in more traffic towards the project.

**Comment by MaskDuck** [comment]
@part1cleth1ef, dns records are not something hideable. theres way to get a dns record publicly. 

for example: [click me to see twitter.com's dns records](https://dnschecker.org/all-dns-records-of-domain.php?query=twitter.com&rtype=ALL&dns=dnsauth)

**Comment by part1cleth1ef** [comment]
@MaskDuck, dns records are actually brute forced generally speaking (most people can't access the zone files)
see https://serverfault.com/questions/16101/how-to-list-all-cname-records-for-a-given-domain

**Comment by wclarkey** [comment]
Theres plently damage someone can do with domain records but it's highly unlikey it will actually happen or fo much damage in our case. Most of our records are CNAME records to GitHub. Meaning that its highly unlikely that the origin server will be affected unless its a large scale ddos. If the record that is being ddosed starts to affect our service we can use Cloudflare's under attack mode. The main idea behind setting up a dashboard is to keep user data safer, this data includes their contact information. We currently include contact information in the records so that we can contact users about any issues or changes with the service. This will be removed and changed when we look towards moving to automating the service and eventually using a dashboard.
Even though we are looking at making the service more private, the dns records are still publically available as with any dns record.

**Comment by wclarkey** [comment]
# Some plans have changed about this
**Automation will still be implemented.**

A dashboard may not be implemented, this is because it will take a lot of maintainance and development time.
The registration will be done the same way as most other projects like this with the help of @Tweak4141.

We will also still be implementing a website.

**Comment by Tweak4141** [comment]
Automation to do:
CI checks and PR automerge.
Annual clean of inactive/unreachable websites.

**Comment by wclarkey** [comment]
Website to do:
- Website static page
- "Menu" like interface before users reach website, easily redirected towards the repo or website

**Comment by wclarkey** [comment]
Other automation:
- Email validation script (*Might not be needed*)

**Comment by DoctorStrange49** [comment]
What do we have to write in record type in json file ?

**Comment by wclarkey** [comment]
> What do we have to write in record type in json file ?

Look at the docs please. https://docs.is-a-good.dev 
And also reply to the comment on your PR

**Comment by wclarkey** [comment]
Todo: 
- Repository housekeeping
- Org housekeeping

**Comment by ConnorDoesDev** [comment]
closed, opened, reopened
my inbox is dying

**Comment by wclarkey** [comment]
oppsie, im not used to using a trackpad
