### ISSUE TITLE
sub-domain is not linking to repl 

### ISSUE THREAD

**Issue by Aarondevp** [is-a-good-dev/register#558]
pls help

**Comment by Aarondevp** [comment]
@nor0x

**Comment by DEV-DIBSTER** [comment]
Most likely because repl doesn't issue SSL certificates.

**Comment by Aarondevp** [comment]
> Most likely because repl doesn't issue SSL certificates.
wdym
@DEV-DIBSTER

**Comment by DEV-DIBSTER** [comment]
> > Most likely because repl doesn't issue SSL certificates.
> 
> wdym @DEV-DIBSTER

You need SSL to connect to a repl instance. We only provide the domain record.

**Comment by Aarondevp** [comment]
what should i do
@DEV-DIBSTER

**Comment by Tweak4141** [comment]
@Aarondevp Please find an alternate hosting service that does issue SSL certificates. SSL is required to use a is-a-good.dev subdomain.
