### ISSUE TITLE
McAfee Marking is-a-good.dev as a Suspicious Site

### ISSUE THREAD

**Issue by avalynndev** [is-a-good-dev/register#620]
As you can see, McAfee is marking your website and all other subdomains as suspicious sites. Please look into the problem and solve it asap.
![image](https://github.com/is-a-good-dev/register/assets/100826194/177efed2-ce60-4894-8336-a7ed8d4d3fc4)

**Comment by clarkedev** [comment]
@Tweak4141 Could you take a look why a landing page might cause this?

I will be putting together a new website soon so it shouldn't be too much of an issue for too long.

**Comment by Tweak4141** [comment]
I've filed an issue with McAfee, and we should see this removed soon.

**Comment by avalynndev** [comment]
![image](https://github.com/is-a-good-dev/register/assets/100826194/fe1ac594-c832-431f-b6c2-47f9329c48f1)
Um It still doesn't seem to change. (Included date as proof)

**Comment by Tweak4141** [comment]
McAfee has resolved our ticket, and this classification should be removed.
