### ISSUE TITLE
Merge into Open Domains

### ISSUE THREAD

**Issue by wdhdev** [is-a-good-dev/register#667]
@wclarkey @Tweak4141 Hi, I'm not sure if this has been suggested before, but Open Domain (https://github.com/open-domains/register) could most likely merge is-a-good.dev into their service, like with Free Domains (https://github.com/free-domains/register).

@andrewstech would need to clarify if we could do this though.

**Comment by clarkedev** [comment]
@wdhdev What benefits would this have?

**Comment by wdhdev** [comment]
@clarkedev Mainly you won't have to pay for the domain anymore and also we already have 4 domains on the Public Suffix List so adding more shouldn't be too difficult.

**Comment by clarkedev** [comment]
@wdhdev What changes would be in place? Would we still manage the project?

**Comment by wdhdev** [comment]
@clarkedev This would be a more or less takeover with this repo being just a redirect like https://github.com/free-domains/register. However you could most likely still have some control over the domain (e.g. CF access to it) however renewal and stuff would be managed by Open Domains.

**Comment by Tweak4141** [comment]
After some further discussion with @clarkedev, we will not be moving forward with this. Thank you for pitching the idea, and your time.
