### ISSUE TITLE
can i become a maintainer

### ISSUE THREAD

**Issue by LogSkele** [is-a-good-dev/Register#83]
hello there, since im very bored these days - can i became a maintainer so i can actually do something useful for once?

if not, no problem. dont be afraid to say so :)

**Comment by wclarkey** [comment]
The only problem with becoming a maintainer, you need a access to Cloudflare which currently has all of my other domains on it too.

**Comment by wclarkey** [comment]
Also with the current scale of the project, 2 maintainers are fine. We don't need anymore right now sorry.
