### ISSUE TITLE
Suggestion: Create a discord server

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [is-a-good-dev/Register#98]
You should create a discord server.

Maybe add a channel where you can request to have your pr merged.

**Comment by Tweak4141** [comment]
Hi there @WilliamDavidHarrison!
We do have a Discord setup, and I'll be working on adding the invite to the readme.

We most likely won't be adding a "request to have your pr merged" channel, as PR's are checked daily.
We also already have a notification web hook setup to bridge between Github and Discord.

**Comment by WilliamDavidHarrison** [comment]
@Tweak4141 can you invite me to the Discord server?

**Comment by Tweak4141** [comment]
https://discord.gg/ksdQmh6Ru2
